/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.JOptionPane;

/**
 *
 * @author Laboratorio-Info
 */
public class Inicio_GUI extends javax.swing.JFrame {

    /**
     * Creates new form Inicio_GUI
     */
    public Inicio_GUI() {
        initComponents();
        RESULTADO_TXT.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        VALOR1_TXT = new javax.swing.JTextField();
        VALOR2_TXT = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        DIVISAO_BTN = new javax.swing.JButton();
        LIMPAR_BTN = new javax.swing.JButton();
        SOMA_BTN1 = new javax.swing.JButton();
        SUBTRACAO_BTN2 = new javax.swing.JButton();
        MULTIPLICACAO_BTN3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        SAIR_BTN1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        RESULTADO_TXT = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 11)); // NOI18N
        jLabel1.setText("VALOR 1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(150, 60, 83, 26);

        VALOR1_TXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VALOR1_TXTActionPerformed(evt);
            }
        });
        jPanel1.add(VALOR1_TXT);
        VALOR1_TXT.setBounds(150, 90, 90, 20);
        jPanel1.add(VALOR2_TXT);
        VALOR2_TXT.setBounds(150, 140, 90, 20);

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 11)); // NOI18N
        jLabel2.setText("RESULTADO");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(150, 170, 70, 15);

        DIVISAO_BTN.setBackground(new java.awt.Color(255, 255, 204));
        DIVISAO_BTN.setText("/");
        DIVISAO_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DIVISAO_BTNActionPerformed(evt);
            }
        });
        jPanel1.add(DIVISAO_BTN);
        DIVISAO_BTN.setBounds(280, 240, 50, 23);

        LIMPAR_BTN.setBackground(new java.awt.Color(255, 88, 59));
        LIMPAR_BTN.setText("LIMPAR");
        LIMPAR_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LIMPAR_BTNActionPerformed(evt);
            }
        });
        jPanel1.add(LIMPAR_BTN);
        LIMPAR_BTN.setBounds(300, 50, 80, 23);

        SOMA_BTN1.setBackground(new java.awt.Color(255, 255, 204));
        SOMA_BTN1.setText("+");
        SOMA_BTN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SOMA_BTN1ActionPerformed(evt);
            }
        });
        jPanel1.add(SOMA_BTN1);
        SOMA_BTN1.setBounds(100, 240, 50, 23);

        SUBTRACAO_BTN2.setBackground(new java.awt.Color(255, 255, 204));
        SUBTRACAO_BTN2.setText("-");
        SUBTRACAO_BTN2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SUBTRACAO_BTN2ActionPerformed(evt);
            }
        });
        jPanel1.add(SUBTRACAO_BTN2);
        SUBTRACAO_BTN2.setBounds(160, 240, 50, 23);

        MULTIPLICACAO_BTN3.setBackground(new java.awt.Color(255, 255, 204));
        MULTIPLICACAO_BTN3.setText("X");
        MULTIPLICACAO_BTN3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MULTIPLICACAO_BTN3ActionPerformed(evt);
            }
        });
        jPanel1.add(MULTIPLICACAO_BTN3);
        MULTIPLICACAO_BTN3.setBounds(220, 240, 50, 23);

        jLabel3.setFont(new java.awt.Font("MingLiU_HKSCS-ExtB", 0, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Calculadora");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(130, 20, 150, 30);

        SAIR_BTN1.setBackground(new java.awt.Color(255, 0, 51));
        SAIR_BTN1.setText("SAIR");
        SAIR_BTN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SAIR_BTN1ActionPerformed(evt);
            }
        });
        jPanel1.add(SAIR_BTN1);
        SAIR_BTN1.setBounds(300, 20, 80, 23);

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 11)); // NOI18N
        jLabel4.setText("VALOR 2");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(150, 120, 59, 15);
        jPanel1.add(RESULTADO_TXT);
        RESULTADO_TXT.setBounds(150, 190, 90, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(400, 300));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LIMPAR_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LIMPAR_BTNActionPerformed
        Model.Funcoes_DAO.limpar();
    }//GEN-LAST:event_LIMPAR_BTNActionPerformed

    private void DIVISAO_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DIVISAO_BTNActionPerformed
        Model.Funcoes_DAO.divisao();
    }//GEN-LAST:event_DIVISAO_BTNActionPerformed

    private void VALOR1_TXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VALOR1_TXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VALOR1_TXTActionPerformed

    private void SOMA_BTN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SOMA_BTN1ActionPerformed
        Model.Funcoes_DAO.soma();
    }//GEN-LAST:event_SOMA_BTN1ActionPerformed

    private void SUBTRACAO_BTN2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SUBTRACAO_BTN2ActionPerformed
         Model.Funcoes_DAO.subtracao();
    }//GEN-LAST:event_SUBTRACAO_BTN2ActionPerformed

    private void MULTIPLICACAO_BTN3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MULTIPLICACAO_BTN3ActionPerformed
        Model.Funcoes_DAO.multiplicacao();
    }//GEN-LAST:event_MULTIPLICACAO_BTN3ActionPerformed

    private void SAIR_BTN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SAIR_BTN1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_SAIR_BTN1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DIVISAO_BTN;
    private javax.swing.JButton LIMPAR_BTN;
    private javax.swing.JButton MULTIPLICACAO_BTN3;
    public static javax.swing.JTextField RESULTADO_TXT;
    private javax.swing.JButton SAIR_BTN1;
    private javax.swing.JButton SOMA_BTN1;
    private javax.swing.JButton SUBTRACAO_BTN2;
    public static javax.swing.JTextField VALOR1_TXT;
    public static javax.swing.JTextField VALOR2_TXT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
