/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author Laboratorio-Info
 */
public class Inicio_GUI extends javax.swing.JFrame {

    /**
     * Creates new form Inicio_GUI
     */
    public Inicio_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        IMC_BTN = new javax.swing.JButton();
        PESO_TXT = new javax.swing.JTextField();
        ALTURA_TXT = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        EXIBIR2_TXT = new javax.swing.JLabel();
        SAIR_BTN = new javax.swing.JButton();
        EXIBIR_TXT = new javax.swing.JLabel();
        LIMPAR_BTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(0));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel1.setText("CALCULADORA DE IMC");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(160, 20, 250, 26);

        IMC_BTN.setBackground(new java.awt.Color(204, 0, 102));
        IMC_BTN.setText("CALCULAR");
        IMC_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IMC_BTNActionPerformed(evt);
            }
        });
        jPanel1.add(IMC_BTN);
        IMC_BTN.setBounds(60, 280, 110, 30);
        jPanel1.add(PESO_TXT);
        PESO_TXT.setBounds(100, 90, 160, 20);

        ALTURA_TXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ALTURA_TXTActionPerformed(evt);
            }
        });
        jPanel1.add(ALTURA_TXT);
        ALTURA_TXT.setBounds(100, 130, 160, 20);

        jLabel2.setFont(new java.awt.Font("Gadugi", 0, 12)); // NOI18N
        jLabel2.setText("Peso:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(50, 90, 40, 20);

        jLabel3.setFont(new java.awt.Font("Gadugi", 0, 12)); // NOI18N
        jLabel3.setText("Altura:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(50, 130, 40, 20);

        EXIBIR2_TXT.setFont(new java.awt.Font("Gadugi", 0, 12)); // NOI18N
        jPanel1.add(EXIBIR2_TXT);
        EXIBIR2_TXT.setBounds(50, 200, 210, 30);

        SAIR_BTN.setBackground(new java.awt.Color(255, 0, 51));
        SAIR_BTN.setText("SAIR");
        SAIR_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SAIR_BTNActionPerformed(evt);
            }
        });
        jPanel1.add(SAIR_BTN);
        SAIR_BTN.setBounds(503, 313, 80, 30);

        EXIBIR_TXT.setFont(new java.awt.Font("Gadugi", 0, 12)); // NOI18N
        jPanel1.add(EXIBIR_TXT);
        EXIBIR_TXT.setBounds(50, 170, 210, 30);

        LIMPAR_BTN.setBackground(new java.awt.Color(255, 153, 0));
        LIMPAR_BTN.setText("LIMPAR");
        LIMPAR_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LIMPAR_BTNActionPerformed(evt);
            }
        });
        jPanel1.add(LIMPAR_BTN);
        LIMPAR_BTN.setBounds(200, 280, 110, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 603, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(603, 359));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ALTURA_TXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ALTURA_TXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ALTURA_TXTActionPerformed

    private void IMC_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IMC_BTNActionPerformed
        Model.Funcoes_DAO.imc();
    }//GEN-LAST:event_IMC_BTNActionPerformed

    private void SAIR_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SAIR_BTNActionPerformed
        Model.Funcoes_DAO.sair();
    }//GEN-LAST:event_SAIR_BTNActionPerformed

    private void LIMPAR_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LIMPAR_BTNActionPerformed
        Model.Funcoes_DAO.limpar();
    }//GEN-LAST:event_LIMPAR_BTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField ALTURA_TXT;
    public static javax.swing.JLabel EXIBIR2_TXT;
    public static javax.swing.JLabel EXIBIR_TXT;
    private javax.swing.JButton IMC_BTN;
    private javax.swing.JButton LIMPAR_BTN;
    public static javax.swing.JTextField PESO_TXT;
    private javax.swing.JButton SAIR_BTN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
