/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import static Model.Pesquisa_DAO.buscarCep;

/**
 *
 * @author Laboratorio-Info
 */
public class Inicio_GUI extends javax.swing.JFrame {

    /**
     * Creates new form Inicio_GUI
     */
    public Inicio_GUI() {
        initComponents();
        ok_img.setVisible(false);
        erro_img.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        cep_txt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        PESQUISAR_BTN = new javax.swing.JButton();
        rua_txt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bairro_txt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cidade_txt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        estado_txt = new javax.swing.JTextField();
        SAIR_BTN = new javax.swing.JButton();
        msg_txt = new javax.swing.JLabel();
        LIMPAR_BTN = new javax.swing.JButton();
        erro_img = new javax.swing.JLabel();
        ok_img = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setLayout(null);

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(0));

        cep_txt.setToolTipText("Digite o CEP com traço (01234-090)");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cep_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(cep_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(20, 30, 210, 50);

        jLabel1.setText("CEP");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(110, 10, 30, 20);

        PESQUISAR_BTN.setText("Pesquisar");
        PESQUISAR_BTN.setToolTipText("Clique para pesquisar");
        PESQUISAR_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PESQUISAR_BTNActionPerformed(evt);
            }
        });
        jPanel1.add(PESQUISAR_BTN);
        PESQUISAR_BTN.setBounds(250, 40, 130, 30);
        jPanel1.add(rua_txt);
        rua_txt.setBounds(20, 120, 210, 20);

        jLabel2.setText("Rua:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 100, 30, 20);

        jLabel3.setText("Cidade:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 180, 50, 20);
        jPanel1.add(bairro_txt);
        bairro_txt.setBounds(20, 160, 210, 20);

        jLabel4.setText("Bairro:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 140, 60, 20);
        jPanel1.add(cidade_txt);
        cidade_txt.setBounds(20, 200, 210, 20);

        jLabel5.setText("Estado:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 220, 60, 20);
        jPanel1.add(estado_txt);
        estado_txt.setBounds(20, 240, 150, 20);

        SAIR_BTN.setText("SAIR");
        SAIR_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SAIR_BTNActionPerformed(evt);
            }
        });
        jPanel1.add(SAIR_BTN);
        SAIR_BTN.setBounds(290, 240, 90, 30);
        jPanel1.add(msg_txt);
        msg_txt.setBounds(240, 90, 150, 30);

        LIMPAR_BTN.setText("Limpar");
        LIMPAR_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LIMPAR_BTNActionPerformed(evt);
            }
        });
        jPanel1.add(LIMPAR_BTN);
        LIMPAR_BTN.setBounds(180, 240, 100, 30);

        erro_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/no.png"))); // NOI18N
        jPanel1.add(erro_img);
        erro_img.setBounds(280, 140, 60, 60);

        ok_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/ok.png"))); // NOI18N
        jPanel1.add(ok_img);
        ok_img.setBounds(280, 140, 60, 60);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(400, 300));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SAIR_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SAIR_BTNActionPerformed
        System.exit(0);
    }//GEN-LAST:event_SAIR_BTNActionPerformed

    private void PESQUISAR_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PESQUISAR_BTNActionPerformed
        buscarCep(cep_txt.getText());
    }//GEN-LAST:event_PESQUISAR_BTNActionPerformed

    private void LIMPAR_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LIMPAR_BTNActionPerformed
        ok_img.setVisible(false);
        erro_img.setVisible(false);
        msg_txt.setText("");
        rua_txt.setText("");
        bairro_txt.setText("");
        cidade_txt.setText("");
        estado_txt.setText("");
    }//GEN-LAST:event_LIMPAR_BTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LIMPAR_BTN;
    private javax.swing.JButton PESQUISAR_BTN;
    private javax.swing.JButton SAIR_BTN;
    public static javax.swing.JTextField bairro_txt;
    public static javax.swing.JTextField cep_txt;
    public static javax.swing.JTextField cidade_txt;
    public static javax.swing.JLabel erro_img;
    public static javax.swing.JTextField estado_txt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public static javax.swing.JLabel msg_txt;
    public static javax.swing.JLabel ok_img;
    public static javax.swing.JTextField rua_txt;
    // End of variables declaration//GEN-END:variables
}
